### ISSUE TITLE
Potential Lua bytecode change

### ISSUE THREAD

**Issue by paulstraw** [t0mg/pd-camera#1]
Hi there! Super cool project, I hope to make one of my own at some point.

I recently referenced your Lua bytecode work, and noticed that the source scripts had hardcoded function names and argument length. I had to work around these restrictions for a project I'm building, and thought you might be interested in the change for yourself.

Here's the relevant file in my code: https://github.com/strawdynamics/pdportal/blob/main/src/lib/util/luaBytecode.ts. This allows:

1. Calling any global function with a name <= 40 chars (after this point, something beyond the normal string bytecode change happens, but I'm not sure what)
2. Passing any length string argument (I've tested up to 100KB in a single call without issue)

**Comment by t0mg** [comment]
Pretty cool! Thanks for the heads up. We don't need it here at the moment but it's really nice to know there's a more flexible solution and it might come in handy in the future. 

pdportal is actually something I was thinking of making myself, I'm glad you're taking on the challenge so I don't have to :)

**Comment by paulstraw** [comment]
Sounds good, it's out there if you need it!
